# Generated by Django 5.1.7 on 2025-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
