# Generated by Django 5.2.1 on 2025-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fcm_token_user_firebase_uid_devicetoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
