# Generated by Django 5.1.7 on 2025-03-12 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_type', models.CharField(choices=[('SPECTATOR', 'Spectator'), ('VICTIM', 'Victim')], max_length=20)),
                ('description', models.TextField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports', to='location.location')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reporter', 'timestamp'], name='emergency_e_reporte_836231_idx')],
            },
        ),
    ]
