# Generated by Django 5.1.7 on 2025-04-11 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emergency_type', models.CharField(choices=[('FIRE', 'Fire Emergency'), ('NATURAL', 'Natural Disaster'), ('TRAFFIC', 'Traffic Accident'), ('OTHER', 'Other Emergency')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reports', to='emergency.emergencytag'),
        ),
    ]
