# Generated by Django 5.2 on 2025-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencytag_emergencyreport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDING', 'Emergency Services Responding'), ('ON_SCENE', 'Emergency Services On Scene'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
