# Generated by Django 5.2.3 on 2025-06-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_emergencyreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='location',
        ),
    ]
