# Generated by Django 5.2.3 on 2025-06-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_remove_emergencyreport_location'),
    ]

    operations = [
        # No operations needed as we already removed the location field in migration 0004
    ]
