# Generated by Django 5.1.7 on 2025-03-12 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Since we're removing the Hazard model, we need to remove these operations
        # If needed, you would need to create a new migration to handle this change properly
    ]
